version: '3'
services:
  web:
    build:
      context: .
    env_file:
      - ./.env.development
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/sample-app
      - public-data:/sample-app/public
      - tmp-data:/sample-app/tmp
      - log-data:/sample-app/log
    depends_on:
      - db
  db:
    image: mysql:5.7
    env_file:
      - ./.env.development
    volumes:
      - db-data:/var/lib/mysql
  nginx:
    build:
      context: nginx/development
    volumes:
      - public-data:/sample-app/public
      - tmp-data:/sample-app/tmp
    ports:
      - 80:80
    depends_on:
      - web
volumes:
  public-data:
  tmp-data:
  log-data:
  db-data:
